In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import ta

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from nsetools import Nse

In [2]:
def get_data(stock):
    df = yf.download(stock, interval="5m", period="5d")

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df.reset_index(drop=True)
    df = df.dropna()

    return df

In [3]:
def add_features(df):
    df = df.copy()

    for col in ['Close','Volume','High','Low']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df['rsi'] = ta.momentum.RSIIndicator(df['Close']).rsi()
    df['ma20'] = df['Close'].rolling(20).mean()
    df['ma50'] = df['Close'].rolling(50).mean()
    df['volume_ma'] = df['Volume'].rolling(20).mean()

    typical_price = (df['High'] + df['Low'] + df['Close']) / 3
    df['vwap'] = (typical_price * df['Volume']).cumsum() / df['Volume'].cumsum()

    return df

In [4]:
def create_target(df):
    df = df.copy()

    close = pd.Series(df['Close'].values, index=df.index)
    future_price = close.shift(-3)

    df['target'] = (future_price > close).astype(int)

    return df

In [5]:
df = get_data("TATASTEEL.NS")
df = add_features(df)
df = create_target(df)

df = df.dropna().reset_index(drop=True)

features = ['rsi','ma20','ma50','volume_ma']

df = df.dropna(subset=features + ['target'])

X = df[features]
y = df['target']

X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

model = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)
model.fit(X_train, y_train)

print("Model Accuracy:", model.score(X_test, y_test))

[*********************100%***********************]  1 of 1 completed

Model Accuracy: 0.48484848484848486

In [6]:
def strategy_filter(df):
    latest = df.iloc[-1]

    return (
        (latest['Close'] > latest['vwap']) and
        (latest['Volume'] > latest['volume_ma']) and
        (latest['Close'] > df['High'].rolling(20).max().iloc[-1])
    )


def generate_trade(df, model):
    latest = df.iloc[-1]

    features = latest[['rsi','ma20','ma50','volume_ma']].fillna(0)

    prob = model.predict_proba(features.values.reshape(1, -1))[0][1]

    if prob > 0.65 and strategy_filter(df):
        return "BUY", prob
    elif prob < 0.35:
        return "SELL", prob

    return "NO TRADE", prob

In [7]:
nifty50 = [
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
    "KOTAKBANK.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","HINDUNILVR.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","NESTLEIND.NS","WIPRO.NS","HCLTECH.NS",
    "BAJFINANCE.NS","BAJAJFINSV.NS","POWERGRID.NS","NTPC.NS","ONGC.NS",
    "COALINDIA.NS","JSWSTEEL.NS","TATASTEEL.NS","INDUSINDBK.NS","TECHM.NS",
    "ADANIENT.NS","ADANIPORTS.NS","BPCL.NS","BRITANNIA.NS","CIPLA.NS",
    "DIVISLAB.NS","DRREDDY.NS","EICHERMOT.NS","GRASIM.NS","HEROMOTOCO.NS",
    "HINDALCO.NS","IOC.NS","M&M.NS","SHREECEM.NS","TATAMOTORS.NS",
    "UPL.NS","BAJAJ-AUTO.NS","SBILIFE.NS","HDFCLIFE.NS","ICICIPRULI.NS"
]

In [8]:
nse = Nse()

gainers = nse.get_top_gainers()
losers = nse.get_top_losers()

gainer_symbols = [s['symbol'] + ".NS" for s in gainers]
loser_symbols = [s['symbol'] + ".NS" for s in losers]

movers = list(set(gainer_symbols + loser_symbols))

In [9]:
final_stocks = list(set(nifty50 + movers))
final_stocks = list(set(nifty50 + movers))

In [10]:
results = []

for stock in final_stocks:
    try:
        temp_df = get_data(stock)
        temp_df = add_features(temp_df)
        temp_df = create_target(temp_df)
        temp_df = temp_df.dropna().reset_index(drop=True)

        signal, prob = generate_trade(temp_df, model)

        results.append({
            "stock": stock,
            "signal": signal,
            "confidence": round(prob, 2)
        })

        print(f"{stock} done ✅")

    except Exception as e:
        print(f"{stock} error ❌", e)

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
$TATAMOTORS.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

TATAMOTORS.NS error ❌ single positional indexer is out-of-bounds

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ICICIBANK.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

NESTLEIND.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

SBIN.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

IOC.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

SHRIRAMFIN.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

MARUTI.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

SUNPHARMA.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

LT.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ITC.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

TRENT.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

TATASTEEL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HDFCLIFE.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HCLTECH.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

MAXHEALTH.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

KOTAKBANK.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ICICIPRULI.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

INFY.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

TECHM.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

NTPC.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

CIPLA.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HEROMOTOCO.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

POWERGRID.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

INDIGO.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

INDUSINDBK.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

GRASIM.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

UPL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

JSWSTEEL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HINDUNILVR.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HINDALCO.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BRITANNIA.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ULTRACEMCO.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BAJAJ-AUTO.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BAJAJFINSV.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BEL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

SBILIFE.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ADANIPORTS.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BPCL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

TCS.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

DIVISLAB.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

RELIANCE.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

EICHERMOT.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ONGC.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

COALINDIA.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ADANIENT.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BHARTIARTL.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

TITAN.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

SHREECEM.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ASIANPAINT.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

BAJFINANCE.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

AXISBANK.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

APOLLOHOSP.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

M&M.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

HDFCBANK.NS done ✅

[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

WIPRO.NS done ✅

[*********************100%***********************]  1 of 1 completed

DRREDDY.NS done ✅

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [11]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(by="confidence", ascending=False)

results_df

            stock    signal  confidence
39    RELIANCE.NS  NO TRADE        0.54
0    ICICIBANK.NS  NO TRADE        0.50
33         BEL.NS  NO TRADE        0.46
21   POWERGRID.NS  NO TRADE        0.45
10   TATASTEEL.NS  NO TRADE        0.45
3          IOC.NS  NO TRADE        0.41
8          ITC.NS  NO TRADE        0.40
53       WIPRO.NS  NO TRADE        0.38
36        BPCL.NS  NO TRADE        0.36
48  BAJFINANCE.NS      SELL        0.34
52    HDFCBANK.NS      SELL        0.31
4   SHRIRAMFIN.NS      SELL        0.31
14   KOTAKBANK.NS      SELL        0.31
49    AXISBANK.NS      SELL        0.28
9        TRENT.NS      SELL        0.28
17       TECHM.NS      SELL        0.28
38    DIVISLAB.NS      SELL        0.28
37         TCS.NS      SELL        0.28
32  BAJAJFINSV.NS      SELL        0.24
41        ONGC.NS      SELL        0.24
35  ADANIPORTS.NS      SELL        0.23
43    ADANIENT.NS      SELL        0.23
42   COALINDIA.NS      SELL        0.23
28    HINDALCO.NS      SELL        0.23
44  BHARTIARTL.NS      SELL        0.23
47  ASIANPAINT.NS      SELL        0.23
31  BAJAJ-AUTO.NS      SELL        0.23
27  HINDUNILVR.NS      SELL        0.23
16        INFY.NS      SELL        0.23
26    JSWSTEEL.NS      SELL        0.23
6    SUNPHARMA.NS      SELL        0.23
23  INDUSINDBK.NS      SELL        0.23
11    HDFCLIFE.NS      SELL        0.23
12     HCLTECH.NS      SELL        0.23
18        NTPC.NS      SELL        0.23
5       MARUTI.NS      SELL        0.22
34     SBILIFE.NS      SELL        0.22
45       TITAN.NS      SELL        0.22
29   BRITANNIA.NS      SELL        0.21
51         M&M.NS      SELL        0.21
15  ICICIPRULI.NS      SELL        0.21
1    NESTLEIND.NS      SELL        0.21
20  HEROMOTOCO.NS      SELL        0.21
25         UPL.NS      SELL        0.21
40   EICHERMOT.NS      SELL        0.20
2         SBIN.NS      SELL        0.20
24      GRASIM.NS      SELL        0.15
30  ULTRACEMCO.NS      SELL        0.15
13   MAXHEALTH.NS      SELL        0.14
19       CIPLA.NS      SELL        0.14
46    SHREECEM.NS      SELL        0.14
22      INDIGO.NS      SELL        0.14
7           LT.NS      SELL        0.14
50  APOLLOHOSP.NS      SELL        0.14
54     DRREDDY.NS      SELL        0.14

In [12]:
best_trades = results_df[
    (results_df["signal"] == "SELL" ) & (results_df["confidence"] > 0.2)
]

best_trades

            stock signal  confidence
48  BAJFINANCE.NS   SELL        0.34
52    HDFCBANK.NS   SELL        0.31
4   SHRIRAMFIN.NS   SELL        0.31
14   KOTAKBANK.NS   SELL        0.31
49    AXISBANK.NS   SELL        0.28
9        TRENT.NS   SELL        0.28
17       TECHM.NS   SELL        0.28
38    DIVISLAB.NS   SELL        0.28
37         TCS.NS   SELL        0.28
32  BAJAJFINSV.NS   SELL        0.24
41        ONGC.NS   SELL        0.24
35  ADANIPORTS.NS   SELL        0.23
43    ADANIENT.NS   SELL        0.23
42   COALINDIA.NS   SELL        0.23
28    HINDALCO.NS   SELL        0.23
44  BHARTIARTL.NS   SELL        0.23
47  ASIANPAINT.NS   SELL        0.23
31  BAJAJ-AUTO.NS   SELL        0.23
27  HINDUNILVR.NS   SELL        0.23
16        INFY.NS   SELL        0.23
26    JSWSTEEL.NS   SELL        0.23
6    SUNPHARMA.NS   SELL        0.23
23  INDUSINDBK.NS   SELL        0.23
11    HDFCLIFE.NS   SELL        0.23
12     HCLTECH.NS   SELL        0.23
18        NTPC.NS   SELL        0.23
5       MARUTI.NS   SELL        0.22
34     SBILIFE.NS   SELL        0.22
45       TITAN.NS   SELL        0.22
29   BRITANNIA.NS   SELL        0.21
51         M&M.NS   SELL        0.21
15  ICICIPRULI.NS   SELL        0.21
1    NESTLEIND.NS   SELL        0.21
20  HEROMOTOCO.NS   SELL        0.21
25         UPL.NS   SELL        0.21

In [13]:
results_df.to_csv("results.csv", index=False)